paths:
  data: 'https://data.heatonresearch.com/data/t81-558/SN_d_tot_V2.0.csv'
  model: 'outputs/model/transformer_model.pth'


sequence:
  size: 10

model parameters:
  batch_size: 32
  epochs: 500
  lr: 0.001
  patience: 5

images:
  zoom: 400